### ISSUE TITLE
frost walker still disabled

### ISSUE THREAD

**Issue by dr-hagar** [sbezboro/standard-groups#10]
Can you add me as a contributor?
(edit: I forked the repo just now)

This particular issue relates of course to:

src/com/sbezboro/standardgroups/listeners/BlockFormListener.java

(a change made by apv a long time ago, and probably accidentally merged (?))

Thanks.

**Comment by dr-hagar** [comment]
Fixed in a fork:

https://github.com/dr-hagar/standard-groups

(as well as a few other things)

**Comment by hiciu** [comment]
Hello,

I see you've commented out limit of 5 locked beds per chunk:

https://github.com/sbezboro/standard-groups/compare/master...dr-hagar:master#diff-3b9daa7d1b1369fd817fb0f5be97a5fdL1386

So, now locked beds will be limited by max-locks-per-chunk (50 or so). Is that on purpose?

(I don't have any opinion on whatever beds should be additionally limited or not.)

**Comment by dr-hagar** [comment]
It just seemed an unnecessary check, the comment "Prevent surrounding chests with locked beds by limiting their number" seems from a time when chests could not be locked (?)

(I guess that can be checked in the history)

**Comment by sbezboro** [comment]
@dr-hagar you can create a pull request from your branch where we can more efficiently discuss and facilitate merging changes in: https://github.com/sbezboro/standard-groups/compare

**Comment by sbezboro** [comment]
Thanks for the PR! This should finally be resolved
